FROM docker.elastic.co/beats/filebeat:7.1.1
MAINTAINER pigtom 13393895196@163.com
COPY ./logstash-filebeat.conf /usr/share/logstash/conf/logstash-filebeat.conf
COPY ./logstash.yml /usr/share/logstash/config/logstash.yml