version: "3"
services:
  es-slave1:
    container_name: es-slave1
    hostname: es-slave1
    image: registry.cn-hangzhou.aliyuncs.com/pigtom/pigtom:v0
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    # 配置网络模式
#    network_mode: "host"
    volumes:
      - ./es/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/logs:/usr/share/elasticsearch/logs
    environment:
      - "TZ=Asia/Shanghai"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  filebeat:
    # 容器名称
    container_name: filebeat
    # 主机名称
    hostname: filebeat
    # 镜像
    image: registry.cn-hangzhou.aliyuncs.com/pigtom/pigtom:filebeat7.1.1
    # 重启机制
    restart: always
    # 持久化挂载
    volumes:
      - ./filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # 映射到容器中[作为数据源]
      - ./logs:/home/project/spring-boot-elasticsearch/logs
      - ./filebeat/logs:/usr/share/filebeat/logs
      - ./filebeat/data:/usr/share/filebeat/data
    environment:
      - "TZ=Asia/Shanghai"
    # 依赖服务[可无]
    depends_on:
      - es-slave1

  spring-boot-elasticsearch:
    container_name: spring-boot-elasticsearch
    image: registry.cn-hangzhou.aliyuncs.com/pigtom/pigtom:spring-boot-es
    restart: always
    working_dir: /home
    # 编译
    ports:
      - 6000:6000
    volumes:
      - ./logs:/logs
    environment:
      - elasticsearch.hosts=http://192.168.0.110:9200
      - PATH=$PATH:/usr/java/jdk/jre1.8.0_241/bin
      - "TZ=Asia/Shanghai"
    depends_on:
      - es-master
    command: java -Xmx200m -jar /app/spring-boot-elasticsearch-1.0.1-SNAPSHOT.jar
