FROM registry.cn-hangzhou.aliyuncs.com/pigtom/pigtom:java8
LABEL Description="This image is just for test" Vendor="pigtom" Version="1.0"
VOLUME /tmp
ADD spring-boot-elasticsearch-1.0.1-SNAPSHOT.jar /app/
EXPOSE 6000